version: '3.9'

services:
  postgres:
    image: postgres:16.1
    container_name: shareit-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shareit

    ports:
      - "5432:5432"

      #- shareit-data:/var/lib/postgresql/data
      # docker-compose up -d
      # docker ps